### ISSUE TITLE
example can't apper

### ISSUE THREAD

**Issue by gyn7561** [steffen/theme-material#2]
http://steffen.github.io/theme-material/extjs-5/examples/conference-manager/
chrome 42
Just see a white page,no error log.
sorry for my poor english

**Comment by steffen** [comment]
Hm, strange, it's working for me, see:

![image](https://cloud.githubusercontent.com/assets/6301/8156635/58e9ac0a-134e-11e5-89da-aeba3fc79214.png)

Can you upgrade to Chrome v43 and test?
What OS are you on?

**Comment by gyn7561** [comment]
thank you. :) it work with vpn. Great Firewall of China intercept access google .
http://fonts.googleapis.com/css?family=Roboto:400,500

**Comment by steffen** [comment]
I created a ticket (#3) to maybe remove that dependency in the future. Glad you found a workaround meanwhile though. :)
